"""
assets/skills/note_taker/scripts/session_summarizer.py
Phase 63: Session Trajectory Summarizer.

Extracts key decisions, failures, and solutions from session trajectories
and generates structured markdown summaries.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any


def summarize(
    session_id: str,
    trajectory: list[dict[str, Any]],
    include_failures: bool = True,
) -> str:
    """Generate markdown summary from session trajectory.

    Args:
        session_id: Unique identifier for this session
        trajectory: List of execution steps with decisions and outcomes
        include_failures: Whether to include failed approaches

    Returns:
        Path to the generated summary file
    """
    # Ensure knowledge directory exists
    knowledge_dir = Path("assets/knowledge/sessions")
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    # Extract session data
    goal = _extract_goal(trajectory)
    decisions = _extract_decisions(trajectory)
    failures = _extract_failures(trajectory) if include_failures else []
    files_modified = _extract_files(trajectory)
    insights = _extract_insights(trajectory)

    # Generate markdown
    timestamp = datetime.utcnow().isoformat()

    markdown = f"""# Session: {session_id}

Date: {timestamp}
Goal: {goal}

## Summary

This session executed {len(trajectory)} steps to achieve the stated goal.

## Decision Path

"""

    for i, decision in enumerate(decisions, 1):
        markdown += f"### {i}. {decision['title']}\n\n"
        markdown += f"**Context**: {decision['context']}\n\n"
        markdown += f"**Choice**: {decision['choice']}\n\n"
        markdown += f"**Rationale**: {decision['rationale']}\n\n"
        if decision.get("alternatives"):
            markdown += f"**Alternatives Considered**:\n"
            for alt in decision["alternatives"]:
                markdown += f"  - {alt}\n"
            markdown += "\n"

    if failures:
        markdown += """## Failed Approaches

"""
        for failure in failures:
            markdown += f"### {failure['approach']}\n\n"
            markdown += f"**Reason**: {failure['reason']}\n\n"
            markdown += f"**Lesson**: {failure['lesson']}\n\n"

    markdown += """## Final Solution

"""
    if decisions:
        final_decision = decisions[-1]
        markdown += f"{final_decision.get('result', 'Task completed successfully.')}\n\n"

    if files_modified:
        markdown += """## Files Modified

"""
        for f in files_modified:
            markdown += f"- `{f['path']}`: {f['description']}\n"
        markdown += "\n"

    if insights:
        markdown += """## Key Insights

"""
        for insight in insights:
            markdown += f"- {insight}\n"
        markdown += "\n"

    markdown += f"""---
*Generated by Note Taker Skill - Session {session_id}*
"""

    # Write to file
    output_path = knowledge_dir / f"{session_id}.md"
    output_path.write_text(markdown)

    return str(output_path)


def _extract_goal(trajectory: list[dict[str, Any]]) -> str:
    """Extract the session goal from trajectory."""
    for step in trajectory:
        if step.get("type") == "goal":
            return step.get("content", "Unknown goal")
    return "Goal not explicitly recorded"


def _extract_decisions(trajectory: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Extract decision points from trajectory."""
    decisions = []
    for step in trajectory:
        if step.get("type") == "decision":
            decisions.append(
                {
                    "title": step.get("title", "Decision"),
                    "context": step.get("context", ""),
                    "choice": step.get("choice", ""),
                    "rationale": step.get("rationale", ""),
                    "alternatives": step.get("alternatives", []),
                    "result": step.get("result", ""),
                }
            )
    return decisions


def _extract_failures(trajectory: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Extract failed approaches from trajectory."""
    failures = []
    for step in trajectory:
        if step.get("type") == "failure":
            failures.append(
                {
                    "approach": step.get("approach", "Unknown approach"),
                    "reason": step.get("reason", "Unknown reason"),
                    "lesson": step.get("lesson", ""),
                }
            )
    return failures


def _extract_files(trajectory: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Extract file modifications from trajectory."""
    files = []
    for step in trajectory:
        if step.get("type") == "file_change":
            files.append(
                {
                    "path": step.get("path", ""),
                    "description": step.get("description", ""),
                }
            )
    return files


def _extract_insights(trajectory: list[dict[str, Any]]) -> list[str]:
    """Extract key insights from trajectory."""
    insights = []
    for step in trajectory:
        if step.get("type") == "insight":
            insights.append(step.get("content", ""))
    return insights
