"""
assets/skills/note_taker/scripts/summarize_session.py
Phase 63: Session Summarization Command.

Summarizes session trajectory into structured markdown notes.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agent.skills.decorators import skill_script


@skill_script(
    name="summarize_session",
    description="Summarize current session trajectory into structured markdown notes",
    category="write",
)
def summarize_session(
    session_id: str,
    trajectory: list[dict[str, Any]],
    include_failures: bool = True,
) -> dict[str, Any]:
    """Extract key decisions, failures, and solutions from session trajectory.

    Args:
        session_id: Unique identifier for this session
        trajectory: List of execution steps with decisions and outcomes
        include_failures: Whether to include failed approaches (default: True)

    Returns:
        Dict with success status and path to generated summary
    """
    # Ensure knowledge directory exists (git-ignored runtime data)
    from common.prj_dirs import PRJ_DATA

    knowledge_dir = PRJ_DATA / "knowledge" / "sessions"
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    # Extract session data
    goal = _extract_goal(trajectory)
    decisions = _extract_decisions(trajectory)
    failures = _extract_failures(trajectory) if include_failures else []
    files_modified = _extract_files(trajectory)
    insights = _extract_insights(trajectory)

    # Generate markdown
    timestamp = datetime.now(timezone.utc).isoformat()

    markdown = f"""# Session: {session_id}

Date: {timestamp}
Goal: {goal}

## Summary

This session executed {len(trajectory)} steps to achieve the stated goal.

## Decision Path

"""

    for i, decision in enumerate(decisions, 1):
        markdown += f"### {i}. {decision['title']}\n\n"
        markdown += f"**Context**: {decision['context']}\n\n"
        markdown += f"**Choice**: {decision['choice']}\n\n"
        markdown += f"**Rationale**: {decision['rationale']}\n\n"
        if decision.get("alternatives"):
            markdown += f"**Alternatives Considered**:\n"
            for alt in decision["alternatives"]:
                markdown += f"  - {alt}\n"
            markdown += "\n"

    if failures:
        markdown += """## Failed Approaches

"""
        for failure in failures:
            markdown += f"### {failure['approach']}\n\n"
            markdown += f"**Reason**: {failure['reason']}\n\n"
            markdown += f"**Lesson**: {failure['lesson']}\n\n"

    markdown += """## Final Solution

"""
    if decisions:
        final_decision = decisions[-1]
        markdown += f"{final_decision.get('result', 'Task completed successfully.')}\n\n"

    if files_modified:
        markdown += """## Files Modified

"""
        for f in files_modified:
            markdown += f"- `{f['path']}`: {f['description']}\n"
        markdown += "\n"

    if insights:
        markdown += """## Key Insights

"""
        for insight in insights:
            markdown += f"- {insight}\n"
        markdown += "\n"

    markdown += f"""---
*Generated by Note Taker Skill - Session {session_id}*
"""

    # Write to file
    output_path = knowledge_dir / f"{session_id}.md"
    output_path.write_text(markdown)

    return {
        "success": True,
        "path": str(output_path),
        "session_id": session_id,
        "decisions_count": len(decisions),
        "failures_count": len(failures),
        "files_count": len(files_modified),
    }


def _extract_goal(trajectory: list[dict[str, Any]]) -> str:
    """Extract the session goal from trajectory."""
    for step in trajectory:
        if step.get("type") == "goal":
            return step.get("content", "Unknown goal")
    return "Goal not explicitly recorded"


def _extract_decisions(trajectory: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Extract decision points from trajectory."""
    decisions = []
    for step in trajectory:
        if step.get("type") == "decision":
            decisions.append(
                {
                    "title": step.get("title", "Decision"),
                    "context": step.get("context", ""),
                    "choice": step.get("choice", ""),
                    "rationale": step.get("rationale", ""),
                    "alternatives": step.get("alternatives", []),
                    "result": step.get("result", ""),
                }
            )
    return decisions


def _extract_failures(trajectory: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Extract failed approaches from trajectory."""
    failures = []
    for step in trajectory:
        if step.get("type") == "failure":
            failures.append(
                {
                    "approach": step.get("approach", "Unknown approach"),
                    "reason": step.get("reason", "Unknown reason"),
                    "lesson": step.get("lesson", ""),
                }
            )
    return failures


def _extract_files(trajectory: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Extract file modifications from trajectory."""
    files = []
    for step in trajectory:
        if step.get("type") == "file_change":
            files.append(
                {
                    "path": step.get("path", ""),
                    "description": step.get("description", ""),
                }
            )
    return files


def _extract_insights(trajectory: list[dict[str, Any]]) -> list[str]:
    """Extract key insights from trajectory."""
    insights = []
    for step in trajectory:
        if step.get("type") == "insight":
            insights.append(step.get("content", ""))
    return insights


if __name__ == "__main__":
    # Test execution
    import json

    test_trajectory = [
        {"type": "goal", "content": "Fix bug in runner.py"},
        {
            "type": "decision",
            "title": "Approach Selection",
            "context": "Need to fix subprocess handling",
            "choice": "Use asyncio.create_subprocess_exec",
            "rationale": "Better async support",
        },
    ]
    result = summarize_session("test_session", test_trajectory)
    print(json.dumps(result, indent=2))
