"""
Vector store error codes and limits.

Single source of truth for validation and runtime error identifiers
used by vector store client and search/hybrid/crud modules.
"""

MAX_SEARCH_RESULTS = 1000

ERROR_REQUEST_VALIDATION = "VECTOR_REQUEST_VALIDATION"
ERROR_BINDING_API_MISSING = "VECTOR_BINDING_API_MISSING"
ERROR_PAYLOAD_VALIDATION = "VECTOR_PAYLOAD_VALIDATION"
ERROR_TABLE_NOT_FOUND = "VECTOR_TABLE_NOT_FOUND"
ERROR_RUNTIME = "VECTOR_RUNTIME_ERROR"
ERROR_HYBRID_PAYLOAD_VALIDATION = "VECTOR_HYBRID_PAYLOAD_VALIDATION"
ERROR_HYBRID_TABLE_NOT_FOUND = "VECTOR_HYBRID_TABLE_NOT_FOUND"
ERROR_HYBRID_RUNTIME = "VECTOR_HYBRID_RUNTIME_ERROR"
