"""
Core Model Factories

生成 Task, Plan, Episode, SubprocessResult 等核心对象的测试数据。

Usage:
    from omni.core.tests.factories import TaskFactory, PlanFactory, SubprocessResultFactory

    task = TaskFactory.build()
    plan = PlanFactory.build()
    result = SubprocessResultFactory.build()
"""

from datetime import UTC, datetime

import pytest
from polyfactory.factories.dataclass_factory import DataclassFactory
from polyfactory.factories.pydantic_factory import ModelFactory

pytestmark = pytest.mark.skip(
    reason="Legacy module deleted - tests preserved for potential future porting"
)

from omni.agent.core.planner.schemas import (
    Episode,
    Plan,
    PlanStatus,
    Task,
    TaskPriority,
    TaskStatus,
)
from omni.agent.core.skill_runtime.support.runner import SubprocessResult


def _utcnow() -> datetime:
    """Get current UTC time."""
    return datetime.now(UTC)


class TaskFactory(ModelFactory[Task]):
    """Factory for generating Task instances."""

    __model__ = Task
    __random_seed__ = 42

    id = "task-001"
    description = "A test task generated by factory"
    status = TaskStatus.PENDING
    priority = TaskPriority.MEDIUM
    dependencies = []
    tool_calls = []
    actual_results = []
    reflection = None
    created_at = None  # Uses default_factory
    started_at = None
    completed_at = None
    metadata = {}


class MinimalTaskFactory(ModelFactory[Task]):
    """Factory for minimal valid Task instances."""

    __model__ = Task
    __random_seed__ = 42

    id = "minimal-task"
    description = "Minimal task"


class PlanFactory(ModelFactory[Plan]):
    """Factory for generating Plan instances."""

    __model__ = Plan
    __random_seed__ = 42

    id = "plan-001"
    goal = "Complete the test goal"
    tasks = []
    current_task_index = 0
    status = PlanStatus.ACTIVE
    created_at = None
    updated_at = None
    metadata = {}


class PlanWithTasksFactory(ModelFactory[Plan]):
    """Factory for generating Plan instances with tasks pre-populated."""

    __model__ = Plan
    __random_seed__ = 42

    id = "plan-with-tasks"
    goal = "A plan with multiple tasks"
    tasks = None  # Will be auto-generated
    current_task_index = 0
    status = PlanStatus.ACTIVE

    @classmethod
    def tasks(cls):
        """Generate 3 tasks with sequential dependencies."""
        return [
            Task(id="task-1", description="First task"),
            Task(id="task-2", description="Second task", dependencies=["task-1"]),
            Task(id="task-3", description="Third task", dependencies=["task-2"]),
        ]


class EpisodeFactory(ModelFactory[Episode]):
    """Factory for generating Episode instances."""

    __model__ = Episode
    __random_seed__ = 42

    id = "episode-001"
    plan_id = "plan-001"
    task_id = "task-001"
    goal = "Test episode goal"
    actions = []
    results = []
    reflection = None
    tokens_used = 0
    duration_seconds = 0.0
    created_at = None


class SubprocessResultFactory(DataclassFactory[SubprocessResult]):
    """Factory for generating SubprocessResult instances (dataclass)."""

    __model__ = SubprocessResult
    __random_seed__ = 42

    success = True
    output = ""
    error = None
    return_code = 0
    duration_ms = 0.0


class SuccessResultFactory(DataclassFactory[SubprocessResult]):
    """Factory for successful subprocess results."""

    __model__ = SubprocessResult
    __random_seed__ = 42

    success = True
    output = "Command executed successfully"
    error = None
    return_code = 0
    duration_ms = 10.5


class ErrorResultFactory(DataclassFactory[SubprocessResult]):
    """Factory for error subprocess results."""

    __model__ = SubprocessResult
    __random_seed__ = 42

    success = False
    output = ""
    error = "Command failed"
    return_code = 1
    duration_ms = 5.0
