"""
MCP Factory

生成 MCP 相关的测试数据：Tools, Resources, Prompts 等。

Usage:
    from omni.core.tests.factories import MCPToolFactory, MCPResourceFactory

    tool = MCPToolFactory.build()
    resource = MCPResourceFactory.build()
"""

from mcp.types import Prompt, Resource, Tool
from polyfactory.factories.pydantic_factory import ModelFactory


class MCPToolFactory(ModelFactory[Tool]):
    """Factory for generating MCP Tool objects."""

    __model__ = Tool
    __random_seed__ = 42

    name = "test_tool"
    description = "A test tool generated by factory"
    inputSchema = {
        "type": "object",
        "properties": {"param1": {"type": "string", "description": "Test parameter"}},
        "required": ["param1"],
    }


class MCPResourceFactory(ModelFactory[Resource]):
    """Factory for generating MCP Resource objects."""

    __model__ = Resource
    __random_seed__ = 42

    uri = "file:///tmp/test.txt"
    name = "test_resource"
    description = "A test resource"
    mimeType = "text/plain"


class MCPPromptFactory(ModelFactory[Prompt]):
    """Factory for generating MCP Prompt objects."""

    __model__ = Prompt
    __random_seed__ = 42

    name = "test_prompt"
    description = "A test prompt"
    arguments = []


class MCPResponseFactory(ModelFactory):
    """Factory for generating mock MCP response objects."""

    __model__ = None  # Not a real Pydantic model
    __random_seed__ = 42

    success = True
    data = {"result": "test"}
    error = None


# =============================================================================
# Convenience Factories
# =============================================================================


class GitToolFactory(ModelFactory[Tool]):
    """Factory for git-related MCP tools."""

    __model__ = Tool
    __random_seed__ = 42

    name = "git_status"
    description = "Show git working tree status"
    inputSchema = {
        "type": "object",
        "properties": {
            "repo_path": {"type": "string", "description": "Repository path"},
            "verbose": {"type": "boolean", "description": "Verbose output"},
        },
    }


class FileToolFactory(ModelFactory[Tool]):
    """Factory for file-related MCP tools."""

    __model__ = Tool
    __random_seed__ = 42

    name = "read_file"
    description = "Read file contents"
    inputSchema = {
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "File path"},
            "encoding": {"type": "string", "description": "File encoding"},
        },
        "required": ["path"],
    }
