"""
Router Model Factories

生成 AgentRoute, RoutingResult, AgentResponse 等路由相关对象的测试数据。

Usage:
    from omni.core.tests.factories import AgentRouteFactory, RoutingResultFactory

    route = AgentRouteFactory.build()
    result = RoutingResultFactory.build()
"""

import pytest
from polyfactory.factories.dataclass_factory import DataclassFactory
from polyfactory.factories.pydantic_factory import ModelFactory

pytestmark = pytest.mark.skip(reason="Module deleted - tests preserved for future reference")

from omni.agent.core.router.models import (
    AgentResponse,
    AgentRoute,
    Decision,
    RoutingResult,
    TaskBrief,
    ToolCall,
)


class AgentRouteFactory(ModelFactory[AgentRoute]):
    """Factory for generating AgentRoute instances."""

    __model__ = AgentRoute
    __random_seed__ = 42

    target_agent = "git"
    confidence = 0.85
    reasoning = "Test route generated by factory"
    task_brief = ""
    constraints = []
    relevant_files = []
    from_cache = False


class CoderAgentRouteFactory(ModelFactory[AgentRoute]):
    """Factory for coder agent routes."""

    __model__ = AgentRoute
    __random_seed__ = 42

    target_agent = "coder"
    confidence = 0.9
    reasoning = "Request involves code writing"


class ReviewerAgentRouteFactory(ModelFactory[AgentRoute]):
    """Factory for reviewer agent routes."""

    __model__ = AgentRoute
    __random_seed__ = 42

    target_agent = "reviewer"
    confidence = 0.9
    reasoning = "Request involves code review"


class RoutingResultFactory(DataclassFactory[RoutingResult]):
    """Factory for generating RoutingResult instances (dataclass)."""

    __model__ = RoutingResult
    __random_seed__ = 42

    selected_skills = ["git"]
    mission_brief = "Show git status"
    reasoning = "Routing based on keyword 'git status'"
    confidence = 0.85
    suggested_skills = []
    remote_suggestions = []
    from_cache = False
    timestamp = None
    env_snapshot = ""


class AgentResponseFactory(ModelFactory[AgentResponse]):
    """Factory for generating AgentResponse instances."""

    __model__ = AgentResponse
    __random_seed__ = 42

    decision = Decision.ACT
    tool_call = None
    handoff_to = None
    message = ""
    confidence = 0.5
    timestamp = None


class ToolCallFactory(ModelFactory[ToolCall]):
    """Factory for generating ToolCall instances."""

    __model__ = ToolCall
    __random_seed__ = 42

    tool = "git.status"
    args = {}


class TaskBriefFactory(ModelFactory[TaskBrief]):
    """Factory for generating TaskBrief instances."""

    __model__ = TaskBrief
    __random_seed__ = 42

    task_description = "Complete the test task"
    constraints = []
    relevant_files = []
    previous_attempts = []
    success_criteria = []
