"""
Manifest Factory

生成 SkillManifest 和相关对象的测试数据。

Usage:
    from agent.tests.factories import SkillManifestFactory

    manifest = SkillManifestFactory.build()
    custom = SkillManifestFactory.build(name="my-skill", version="2.0.0")
"""

from typing import Any
from polyfactory.factories.pydantic_factory import ModelFactory
from agent.core.schema.skill import SkillManifest, SkillDependencies


class SkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory for generating valid SkillManifest instances.

    Features:
    - Auto-generates type-compliant data for all fields
    - Supports field overrides via kwargs
    - Generates consistent sequences with deterministic defaults
    - Compatible with Pydantic v2
    """

    __model__ = SkillManifest

    # Deterministic defaults for reproducible tests
    manifest_version = "1.0.0"
    type = "skill"
    name = "test_skill"
    version = "0.1.0"
    description = "A test skill generated by polyfactory"
    author = "omni-dev-fusion"
    license = "Apache-2.0"
    tools_module = "agent.skills.test.tools"
    guide_file = "README.md"
    routing_keywords = ["test", "factory"]
    intents = ["test_intent"]
    dependencies = SkillDependencies()


class MinimalSkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory for minimal valid manifests (only required fields)."""

    __model__ = SkillManifest

    name = "minimal_skill"
    version = "0.1.0"
    description = "Minimal test skill"
    tools_module = "agent.skills.minimal.tools"


class ValidSkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory for fully-featured valid manifests."""

    __model__ = SkillManifest

    manifest_version = "1.0.0"
    type = "skill"
    name = "fully_featured_skill"
    version = "2.3.1"
    description = "A comprehensive test skill with all optional fields"
    author = "Test Suite"
    license = "Apache-2.0"
    tools_module = "agent.skills.fully_featured.tools"
    routing_keywords = ["testing", "factory", "pydantic"]
    intents = ["test", "demo"]
    repository = {"type": "github", "url": "https://github.com/test/skill", "directory": "."}


# =============================================================================
# Skill-Specific Factories
# =============================================================================


class GitSkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory mimicking the git skill manifest."""

    __model__ = SkillManifest

    name = "git"
    version = "1.0.0"
    description = "Git operations skill - commit, status, branch management"
    tools_module = "agent.skills.git.tools"
    routing_keywords = ["git", "commit", "push", "branch", "clone"]
    intents = ["git_operations", "version_control"]
    author = "omni-dev-fusion"


class FilesystemSkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory mimicking the filesystem skill manifest."""

    __model__ = SkillManifest

    name = "filesystem"
    version = "1.0.0"
    description = "Filesystem operations - read, write, list, search files"
    tools_module = "agent.skills.filesystem.tools"
    routing_keywords = ["file", "filesystem", "read", "write", "list"]
    intents = ["file_operations", "io"]
    author = "omni-dev-fusion"


class KnowledgeSkillManifestFactory(ModelFactory[SkillManifest]):
    """Factory mimicking the knowledge skill manifest."""

    __model__ = SkillManifest

    name = "knowledge"
    version = "1.0.0"
    description = "Knowledge base and RAG operations"
    tools_module = "agent.skills.knowledge.tools"
    routing_keywords = ["knowledge", "rag", "search", "query"]
    intents = ["knowledge_retrieval", "rag"]
    author = "omni-dev-fusion"


# =============================================================================
# Factory Instances for Direct Use
# =============================================================================


#: Default factory for SkillManifest
skill_manifest = SkillManifestFactory

#: Factory for minimal valid manifests
minimal_manifest = MinimalSkillManifestFactory

#: Factory for git-like skill manifests
git_manifest = GitSkillManifestFactory

#: Factory for filesystem-like skill manifests
filesystem_manifest = FilesystemSkillManifestFactory

#: Factory for knowledge-like skill manifests
knowledge_manifest = KnowledgeSkillManifestFactory


# =============================================================================
# Documentation Examples
# =============================================================================
"""
Usage Examples:

# 1. Basic usage - auto-generate all fields
def test_manifest_has_all_fields():
    manifest = SkillManifestFactory.build()
    assert isinstance(manifest, SkillManifest)
    assert manifest.name is not None
    assert manifest.version is not None

# 2. With field overrides - customize specific fields
def test_manifest_with_custom_name():
    manifest = SkillManifestFactory.build(
        name="my-custom-skill",
        version="3.0.0",
        description="Custom description"
    )
    assert manifest.name == "my-custom-skill"
    assert manifest.version == "3.0.0"

# 3. Batch generation - create multiple instances
def test_batch_manifests():
    manifests = SkillManifestFactory.batch(size=10)
    assert len(manifests) == 10
    assert all(isinstance(m, SkillManifest) for m in manifests)

# 4. Skill-specific factory
def test_git_skill_manifest():
    manifest = GitSkillManifestFactory.build()
    assert manifest.name == "git"
    assert "git" in manifest.routing_keywords

# 5. Fixture-based usage
@pytest.fixture
def sample_manifest():
    return SkillManifestFactory.build()

def test_using_fixture(sample_manifest):
    assert sample_manifest.name is not None
"""
