"""
MCP Factory

生成 MCP 相关的测试数据：Tools, Resources, Prompts 等。
"""

from typing import Any, Optional
from polyfactory.factories.pydantic_factory import ModelFactory


class MCPToolFactory(ModelFactory):
    """Factory for generating MCP Tool objects.

    Usage:
        from agent.tests.factories import MCPToolFactory

        tool = MCPToolFactory.build()
        assert tool.name is not None

        # With overrides
        tool = MCPToolFactory.build(name="custom_tool", description="Custom description")
    """

    __model__: Any = None  # Set to actual MCP Tool class

    name = "test_tool"
    description = "A test tool generated by factory"
    input_schema = {
        "type": "object",
        "properties": {"param1": {"type": "string", "description": "Test parameter"}},
        "required": ["param1"],
    }


class MCPResourceFactory(ModelFactory):
    """Factory for generating MCP Resource objects."""

    __model__: Any = None  # Set to actual MCP Resource class

    uri = "file:///tmp/test.txt"
    name = "test_resource"
    description = "A test resource"
    mime_type = "text/plain"


class MCPPromptFactory(ModelFactory):
    """Factory for generating MCP Prompt objects."""

    __model__: Any = None  # Set to actual MCP Prompt class

    name = "test_prompt"
    description = "A test prompt"
    arguments = []


class MCPResponseFactory(ModelFactory):
    """Factory for generating mock MCP response objects."""

    __model__: Any = None

    success = True
    data = {"result": "test"}
    error = None


# =============================================================================
# Convenience Factories
# =============================================================================


class GitToolFactory(ModelFactory):
    """Factory for git-related MCP tools."""

    __model__: Any = None

    name = "git_status"
    description = "Show git working tree status"
    input_schema = {
        "type": "object",
        "properties": {
            "repo_path": {"type": "string", "description": "Repository path"},
            "verbose": {"type": "boolean", "description": "Verbose output"},
        },
    }


class FileToolFactory(ModelFactory):
    """Factory for file-related MCP tools."""

    __model__: Any = None

    name = "read_file"
    description = "Read file contents"
    input_schema = {
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "File path"},
            "encoding": {"type": "string", "description": "File encoding"},
        },
        "required": ["path"],
    }


# =============================================================================
# Documentation Examples
# =============================================================================
"""
Usage Examples:

# 1. Basic tool generation
def test_tool_has_name():
    from agent.tests.factories import MCPToolFactory
    tool = MCPToolFactory.build()
    assert tool.name is not None

# 2. Custom tool
def test_custom_tool():
    from agent.tests.factories import MCPToolFactory
    tool = MCPToolFactory.build(
        name="my_tool",
        description="My custom tool description"
    )
    assert tool.name == "my_tool"

# 3. Git-specific tool
def test_git_tool():
    from agent.tests.factories import GitToolFactory
    tool = GitToolFactory.build()
    assert "git" in tool.name

# 4. Response factory
def test_mock_response():
    from agent.tests.factories import MCPResponseFactory
    response = MCPResponseFactory.build(data={"status": "ok"})
    assert response.success is True
    assert response.data["status"] == "ok"
"""
