"""
Skill Metadata Factory

生成 SkillMetadata 和相关对象的测试数据。

Usage:
    from agent.tests.factories import SkillMetadataFactory

    metadata = SkillMetadataFactory.build()
    custom = SkillMetadataFactory.build(name="my-skill", version="2.0.0")
"""

from typing import Any
from polyfactory.factories.pydantic_factory import ModelFactory
from agent.core.schema.skill import SkillMetadata, SkillDependencies


class SkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory for generating valid SkillMetadata instances.

    Features:
    - Auto-generates type-compliant data for all fields
    - Supports field overrides via kwargs
    - Generates consistent sequences with deterministic defaults
    - Compatible with Pydantic v2
    """

    __model__ = SkillMetadata

    # Deterministic defaults for reproducible tests
    metadata_version = "1.0.0"
    type = "skill"
    name = "test_skill"
    version = "0.1.0"
    description = "A test skill generated by polyfactory"
    author = "omni-dev-fusion"
    license = "Apache-2.0"
    commands_module = "scripts"
    guide_file = "README.md"
    routing_keywords = ["test", "factory"]
    intents = ["test_intent"]
    dependencies = SkillDependencies()


class MinimalSkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory for minimal valid metadata (only required fields)."""

    __model__ = SkillMetadata

    name = "minimal_skill"
    version = "0.1.0"
    description = "Minimal test skill"
    commands_module = "scripts"


class ValidSkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory for fully-featured valid metadata."""

    __model__ = SkillMetadata

    metadata_version = "1.0.0"
    type = "skill"
    name = "fully_featured_skill"
    version = "2.3.1"
    description = "A comprehensive test skill with all optional fields"
    author = "Test Suite"
    license = "Apache-2.0"
    commands_module = "scripts"
    routing_keywords = ["testing", "factory", "pydantic"]
    intents = ["test", "demo"]
    repository = {"type": "github", "url": "https://github.com/test/skill", "directory": "."}


# =============================================================================
# Skill-Specific Factories
# =============================================================================


class GitSkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory mimicking the git skill metadata."""

    __model__ = SkillMetadata

    name = "git"
    version = "1.0.0"
    description = "Git operations skill - commit, status, branch management"
    commands_module = "scripts"
    routing_keywords = ["git", "commit", "push", "branch", "clone"]
    intents = ["git_operations", "version_control"]
    author = "omni-dev-fusion"


class FilesystemSkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory mimicking the filesystem skill metadata."""

    __model__ = SkillMetadata

    name = "filesystem"
    version = "1.0.0"
    description = "Filesystem operations - read, write, list, search files"
    commands_module = "scripts"
    routing_keywords = ["file", "filesystem", "read", "write", "list"]
    intents = ["file_operations", "io"]
    author = "omni-dev-fusion"


class KnowledgeSkillMetadataFactory(ModelFactory[SkillMetadata]):
    """Factory mimicking the knowledge skill metadata."""

    __model__ = SkillMetadata

    name = "knowledge"
    version = "1.0.0"
    description = "Knowledge base and RAG operations"
    commands_module = "scripts"
    routing_keywords = ["knowledge", "rag", "search", "query"]
    intents = ["knowledge_retrieval", "rag"]
    author = "omni-dev-fusion"


# =============================================================================
# Factory Instances for Direct Use
# =============================================================================


#: Default factory for SkillMetadata
skill_metadata = SkillMetadataFactory

#: Factory for minimal valid metadata
minimal_metadata = MinimalSkillMetadataFactory

#: Factory for git-like skill metadata
git_metadata = GitSkillMetadataFactory

#: Factory for filesystem-like skill metadata
filesystem_metadata = FilesystemSkillMetadataFactory

#: Factory for knowledge-like skill metadata
knowledge_metadata = KnowledgeSkillMetadataFactory


# =============================================================================
# Documentation Examples
# =============================================================================
"""
Usage Examples:

# 1. Basic usage - auto-generate all fields
def test_metadata_has_all_fields():
    metadata = SkillMetadataFactory.build()
    assert isinstance(metadata, SkillMetadata)
    assert metadata.name is not None
    assert metadata.version is not None

# 2. With field overrides - customize specific fields
def test_metadata_with_custom_name():
    metadata = SkillMetadataFactory.build(
        name="my-custom-skill",
        version="3.0.0",
        description="Custom description"
    )
    assert metadata.name == "my-custom-skill"
    assert metadata.version == "3.0.0"

# 3. Batch generation - create multiple instances
def test_batch_metadata():
    metadata_list = SkillMetadataFactory.batch(size=10)
    assert len(metadata_list) == 10
    assert all(isinstance(m, SkillMetadata) for m in metadata_list)

# 4. Skill-specific factory
def test_git_skill_metadata():
    metadata = GitSkillMetadataFactory.build()
    assert metadata.name == "git"
    assert "git" in metadata.routing_keywords

# 5. Fixture-based usage
@pytest.fixture
def sample_metadata():
    return SkillMetadataFactory.build()

def test_using_fixture(sample_metadata):
    assert sample_metadata.name is not None
"""
