"""
omni.core.skills.discovery - Skill Discovery Module

High-performance skill discovery using Rust-generated Index.
Replaces live file system scanning with Read-Only Index consumption.

Architecture:
    Index (JSON) -> Foundation (Reader) -> Core (Discovery) -> Kernel

    ┌─────────────────┐
    │ skill_index.json│  ← Generated by Rust Scanner
    └────────┬────────┘
             │
             ▼ Reads
    ┌─────────────────┐
    │PythonSkillScanner│  ← Foundation Layer (Index Reader)
    └────────┬────────┘
             │
             ▼ Returns
    ┌─────────────────┐
    │DiscoveredSkill  │  ← Core Layer (Discovery Service)
    └────────┬────────┘
             │
             ▼ Used by
    ┌─────────────────┐
    │   Kernel        │  ← Consumes DiscoveredSkill objects
    └─────────────────┘
"""

import os
from typing import Any

from omni.foundation.bridge.scanner import (
    DiscoveredSkillRules,
    PythonSkillScanner,
)
from omni.foundation.config.logging import get_logger
from pydantic import BaseModel

logger = get_logger("omni.core.discovery")


class DiscoveredSkill(BaseModel):
    """Represents a discovered skill with its metadata.

    Created from Foundation's DiscoveredSkillRules via from_index_entry().
    """

    name: str
    path: str
    metadata: dict[str, Any]
    has_extensions: bool = False

    @classmethod
    def from_index_entry(cls, entry: DiscoveredSkillRules) -> "DiscoveredSkill":
        """Create from Foundation DiscoveredSkillRules object.

        Args:
            entry: DiscoveredSkillRules from PythonSkillScanner.scan_directory()

        Returns:
            DiscoveredSkill instance
        """
        # Check for extensions directory
        has_ext = False
        if entry.skill_path:
            ext_path = os.path.join(entry.skill_path, "extensions")
            has_ext = os.path.isdir(ext_path)

        return cls(
            name=entry.skill_name,
            path=entry.skill_path,
            metadata=entry.metadata,
            has_extensions=has_ext,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any], name: str, path: str) -> "DiscoveredSkill":
        """Create from raw dictionary (for testing/fallback).

        Args:
            data: Dictionary with skill metadata
            name: Skill name
            path: Skill path

        Returns:
            DiscoveredSkill instance
        """
        has_ext = os.path.isdir(os.path.join(path, "extensions"))
        return cls(
            name=name,
            path=path,
            metadata=data,
            has_extensions=has_ext,
        )


class SkillDiscoveryService:
    """
    Level 2: Skill Discovery Service.

    Coordinates skill discovery using the Single Source of Truth (Index).
    This provides O(1) discovery time regardless of skill count.

    Usage:
        service = SkillDiscoveryService()
        skills = service.discover_all()  # Reads skill_index.json
        for skill in skills:
            print(f"Found: {skill.name}")
    """

    def __init__(self):
        """Initialize the discovery service with Index Reader."""
        self._scanner = PythonSkillScanner()

    def discover_all(self, locations: list[str] | None = None) -> list[DiscoveredSkill]:
        """Discover all skills from the Index.

        Args:
            locations: Ignored in Rust-First Indexing (kept for API compat).
                       The index location is resolved by the Foundation layer.

        Returns:
            List of DiscoveredSkill objects sorted by name.
        """
        logger.debug("🔍 Accessing Skill Index...")

        # Use Foundation Layer to read JSON Index
        index_entries = self._scanner.scan_directory()

        all_skills = []
        for entry in index_entries:
            skill = DiscoveredSkill.from_index_entry(entry)
            all_skills.append(skill)

        # Sort by name for consistent ordering
        all_skills.sort(key=lambda s: s.name)

        logger.info(f"📦 Index Service provided {len(all_skills)} skills")
        return all_skills

    def discover_one(self, skill_name: str) -> DiscoveredSkill | None:
        """Find a single skill in the Index by name.

        Args:
            skill_name: Name of the skill to find.

        Returns:
            DiscoveredSkill if found, None otherwise.
        """
        # This scans the in-memory list (fast enough for now)
        skills = self.discover_all()
        for skill in skills:
            if skill.name == skill_name:
                return skill
        return None

    def get_skills_with_extensions(self) -> list[DiscoveredSkill]:
        """Get all skills that have extensions directory."""
        skills = self.discover_all()
        return [s for s in skills if s.has_extensions]


def is_rust_available() -> bool:
    """Check if Rust bindings are available.

    Note: In Rust-First Indexing, this returns True if the index
    was generated by the Rust scanner (which is always the case now).
    """
    return True


__all__ = [
    "DiscoveredSkill",
    "SkillDiscoveryService",
    "is_rust_available",
]
